<?php

$products = [
    'quarrying-wire-saw' => [
        'id' => 'quarrying-wire-saw',
        'name' => 'Quarrying Wire Saw',
        'category' => 'Wire Saws',
        'hero' => [
            'image' => 'assets/images/products/quarrying-wire-hero.jpg',
            'tagline' => 'Premium Quality',
            'description' => 'Heavy-duty diamond wire saw engineered for large-scale stone extraction in quarries. Maximum cutting efficiency with minimal operational costs.',
        ],
        'quickStats' => [
            ['label' => 'Wire Diameter', 'value' => '11.5mm'],
            ['label' => 'Bead Density', 'value' => '40 beads/m'],
            ['label' => 'Tensile Strength', 'value' => '2200 MPa'],
            ['label' => 'Cutting Speed', 'value' => '5-10 m²/h'],
        ],
        'overview' => [
            'mainImage' => 'assets/images/products/quarrying-main.jpg',
            'badge' => 'Made in India',
            'galleryImages' => [
                'assets/images/products/quarrying-detail-1.jpg',
                'assets/images/products/quarrying-detail-2.jpg',
                'assets/images/products/quarrying-detail-3.jpg',
            ],
            'title' => 'Professional Grade Quarrying Solution',
            'description1' => 'Our Quarrying Wire Saw is specifically designed for high-volume stone extraction in granite, marble, and limestone quarries. With reinforced steel cable construction and premium diamond beads, this wire delivers exceptional performance even in the most demanding cutting conditions.',
            'description2' => 'Engineered to minimize downtime and maximize productivity, our quarrying wire saw provides consistent cutting performance with extended service life. The optimal bead spacing and high-tensile wire rope ensure smooth operation and reduced operational costs.',
            'keyFeatures' => [
                ['title' => 'High Tensile Strength Wire Rope', 'desc' => '2200 MPa strength ensures durability in heavy-duty applications'],
                ['title' => 'Premium Diamond Beads', 'desc' => 'Superior cutting efficiency with consistent performance'],
                ['title' => 'Optimized Bead Spacing', 'desc' => '40 beads per meter for balanced cutting and longevity'],
                ['title' => 'Extended Service Life', 'desc' => 'Cuts 1000-1500 m² per wire under optimal conditions'],
            ],
            'certifications' => 'ISO 9001:2015 | CE Certified | 100% Quality Tested',
        ],
        'applications' => [
            ['title' => 'Granite Quarrying', 'image' => 'assets/images/applications/granite-quarry.jpg', 'desc' => 'Exceptional performance in hard granite extraction with consistent cutting speed and minimal wire breakage. Ideal for large block cutting.'],
            ['title' => 'Marble Extraction', 'image' => 'assets/images/applications/marble-quarry.jpg', 'desc' => 'Smooth, clean cuts in marble quarries with reduced material wastage. Perfect for premium quality block extraction.'],
            ['title' => 'Limestone Quarrying', 'image' => 'assets/images/applications/limestone-quarry.jpg', 'desc' => 'Efficient cutting in limestone and sandstone quarries. Cost-effective solution for high-volume operations.'],
            ['title' => 'Basalt & Hard Stone', 'image' => 'assets/images/applications/basalt-quarry.jpg', 'desc' => 'Specially formulated for extremely hard stone types. High diamond concentration ensures effective cutting.'],
            ['title' => 'Block Squaring', 'image' => 'assets/images/applications/block-squaring.jpg', 'desc' => 'Precise squaring and trimming of rough blocks. Reduces waste and improves block quality for further processing.'],
            ['title' => 'Large Block Cutting', 'image' => 'assets/images/applications/large-blocks.jpg', 'desc' => 'Designed for cutting massive stone blocks in primary extraction. High stability and controlled cutting path.'],
        ],
        'specifications' => [
            ['param' => 'Wire Diameter', 'spec' => '11.5mm ± 0.2mm'],
            ['param' => 'Bead Diameter', 'spec' => '10.5mm - 11.0mm'],
            ['param' => 'Bead Spacing', 'spec' => '40 beads/meter'],
            ['param' => 'Wire Rope Construction', 'spec' => '6×19 + 1 FC / 7×7 structure'],
            ['param' => 'Breaking Load (Tensile Strength)', 'spec' => '≥ 2200 MPa (≥ 2500 kg)'],
            ['param' => 'Diamond Concentration', 'spec' => '25% - 30% (customizable)'],
            ['param' => 'Diamond Mesh Size', 'spec' => '30/35, 35/40, 40/45, 45/50'],
            ['param' => 'Bead Connection Method', 'spec' => 'Injection molding / Rubber + Spring'],
            ['param' => 'Cutting Speed', 'spec' => '5-10 m²/hour (varies by stone type)'],
            ['param' => 'Lifespan (Granite)', 'spec' => '1000-1500 m² per wire'],
            ['param' => 'Recommended Cutting Speed', 'spec' => '28-32 m/s (linear speed)'],
            ['param' => 'Recommended Wire Tension', 'spec' => '800-1200 kg'],
            ['param' => 'Water Flow Rate', 'spec' => '80-120 liters/minute'],
            ['param' => 'Standard Length', 'spec' => 'Custom (typically 20m - 80m loops)'],
            ['param' => 'Packaging', 'spec' => 'Wooden case or carton box'],
        ],
        'advantages' => [
            ['icon' => 'lightning', 'title' => 'High Cutting Efficiency', 'desc' => 'Optimized bead design and diamond distribution deliver faster cutting speeds, reducing extraction time and increasing daily output.'],
            ['icon' => 'coins', 'title' => 'Cost-Effective Operation', 'desc' => 'Extended wire life and reduced power consumption translate to lower cost per square meter, improving profitability.'],
            ['icon' => 'shield-check', 'title' => 'Superior Durability', 'desc' => 'High-tensile steel wire rope with reinforced bead connections ensures minimal wire breakage even in demanding conditions.'],
            ['icon' => 'paintbrush', 'title' => 'Smooth Cutting Surface', 'desc' => 'Precision-engineered beads create clean, smooth cuts with minimal surface roughness, reducing secondary processing requirements.'],
            ['icon' => 'gears', 'title' => 'Customizable Solutions', 'desc' => 'Tailored specifications available for different stone types, hardness levels, and specific quarry requirements.'],
            ['icon' => 'headset', 'title' => 'Technical Support', 'desc' => 'Expert guidance on wire selection, installation, operation parameters, and troubleshooting from our experienced team.'],
        ],
        'guidelines' => [
            'installation' => [
                'Inspect wire for any damage before installation',
                'Ensure proper wire tension (800-1200 kg recommended)',
                'Check pulley alignment and groove condition',
                'Verify water cooling system is functioning properly',
                'Run wire at low speed initially to seat beads properly',
            ],
            'operation' => [
                'Maintain linear speed of 28-32 m/s for optimal performance',
                'Ensure continuous water flow (80-120 liters/minute)',
                'Monitor wire tension throughout operation',
                'Avoid sudden starts and stops to prevent wire breakage',
                'Regularly check for unusual vibrations or noises',
            ],
            'maintenance' => [
                'Clean wire and beads after each shift',
                'Inspect pulleys and bearings for wear weekly',
                'Check water nozzles for blockages regularly',
                'Lubricate machine moving parts as per schedule',
                'Store unused wire in dry, covered conditions',
            ],
            'safety' => [
                'Wear appropriate PPE (goggles, gloves, hearing protection)',
                'Keep safe distance from operating wire saw',
                'Never touch wire during operation',
                'Ensure emergency stop button is accessible',
                'Train operators on proper safety procedures',
            ],
        ],
        'relatedProducts' => [
            ['slug' => 'diamond-wire-saw', 'title' => 'Diamond Wire Saw', 'image' => 'assets/images/products/diamond-wire.jpg', 'desc' => 'Multi-purpose diamond wire for block squaring and profiling operations.'],
            ['slug' => 'mono-wire', 'title' => 'Mono (Stationary) Wire', 'image' => 'assets/images/products/mono-wire.jpg', 'desc' => 'Stationary wire saw for precise cutting in stone processing facilities.'],
            ['slug' => 'diamond-beads', 'title' => 'Diamond Wiresaw Beads', 'image' => 'assets/images/products/diamond-beads.jpg', 'desc' => 'Premium diamond beads for wire saw assembly and replacements.'],
        ],
        'contact' => [
            'phone1' => '+91 99288 11486',
            'phone2' => '+91 90240 34737',
            'email' => 'cdtools8189@gmail.com',
        ],
    ],

    'diamond-wire-saw' => [
        'id' => 'diamond-wire-saw',
        'name' => 'Diamond Wire Saw',
        'category' => 'Wire Saws',
        'hero' => [
            'image' => 'assets/images/products/diamond-wire-hero.jpg',
            'tagline' => 'Versatile Cutting',
            'description' => 'Multi-purpose diamond wire saw engineered for block squaring, profiling, and precision cutting operations. Ideal for both primary and secondary processing.',
        ],
        'quickStats' => [
            ['label' => 'Wire Diameter', 'value' => '10.5mm'],
            ['label' => 'Bead Density', 'value' => '45 beads/m'],
            ['label' => 'Tensile Strength', 'value' => '2000 MPa'],
            ['label' => 'Cutting Speed', 'value' => '8-15 m²/h'],
        ],
        'overview' => [
            'mainImage' => 'assets/images/products/diamond-wire-main.jpg',
            'badge' => 'Made in India',
            'galleryImages' => [
                'assets/images/products/diamond-wire-detail-1.jpg',
                'assets/images/products/diamond-wire-detail-2.jpg',
                'assets/images/products/diamond-wire-detail-3.jpg',
            ],
            'title' => 'Precision Multi-Purpose Solution',
            'description1' => 'Our Diamond Wire Saw is engineered for versatile stone processing applications including block squaring, edge profiling, and precision cutting. With advanced diamond concentration and optimized bead spacing, it delivers superior cutting performance across various stone types.',
            'description2' => 'Perfect for both quarries and stone processing facilities, this wire saw combines efficiency with precision. The balanced design ensures consistent performance while minimizing material wastage and reducing operational costs.',
            'keyFeatures' => [
                ['title' => 'Premium Diamond Distribution', 'desc' => 'Optimized diamond concentration for superior cutting efficiency'],
                ['title' => 'Precision Bead Spacing', 'desc' => '45 beads per meter for fine finishing and accuracy'],
                ['title' => 'Versatile Application', 'desc' => 'Suitable for both primary extraction and secondary processing'],
                ['title' => 'Extended Lifespan', 'desc' => 'Cuts 1200-1800 m² per wire under optimal conditions'],
            ],
            'certifications' => 'ISO 9001:2015 | CE Certified | 100% Quality Tested',
        ],
        'applications' => [
            ['title' => 'Block Squaring', 'image' => 'assets/images/applications/block-squaring.jpg', 'desc' => 'Precise squaring of rough blocks with minimal material loss and excellent surface finish.'],
            ['title' => 'Edge Profiling', 'image' => 'assets/images/applications/edge-profiling.jpg', 'desc' => 'Create beveled edges and decorative profiles on stone slabs with precision.'],
            ['title' => 'Slab Cutting', 'image' => 'assets/images/applications/slab-cutting.jpg', 'desc' => 'Clean, straight cuts for dividing large slabs into market-ready dimensions.'],
            ['title' => 'Granite Processing', 'image' => 'assets/images/applications/granite-processing.jpg', 'desc' => 'Efficient processing of granite blocks and slabs in stone facilities.'],
            ['title' => 'Marble Finishing', 'image' => 'assets/images/applications/marble-finishing.jpg', 'desc' => 'Smooth finishing cuts on marble with minimal chipping and breakage.'],
            ['title' => 'Limestone Processing', 'image' => 'assets/images/applications/limestone-processing.jpg', 'desc' => 'Versatile cutting solution for limestone and similar soft stone types.'],
        ],
        'specifications' => [
            ['param' => 'Wire Diameter', 'spec' => '10.5mm ± 0.2mm'],
            ['param' => 'Bead Diameter', 'spec' => '9.5mm - 10.0mm'],
            ['param' => 'Bead Spacing', 'spec' => '45 beads/meter'],
            ['param' => 'Wire Rope Construction', 'spec' => '6×19 + 1 FC structure'],
            ['param' => 'Breaking Load (Tensile Strength)', 'spec' => '≥ 2000 MPa (≥ 2200 kg)'],
            ['param' => 'Diamond Concentration', 'spec' => '30% - 35% (customizable)'],
            ['param' => 'Diamond Mesh Size', 'spec' => '35/40, 40/45, 45/50, 50/60'],
            ['param' => 'Bead Connection Method', 'spec' => 'Injection molding / Rubber + Spring'],
            ['param' => 'Cutting Speed', 'spec' => '8-15 m²/hour (varies by application)'],
            ['param' => 'Lifespan (Mixed Stone)', 'spec' => '1200-1800 m² per wire'],
            ['param' => 'Recommended Cutting Speed', 'spec' => '30-35 m/s (linear speed)'],
            ['param' => 'Recommended Wire Tension', 'spec' => '700-1000 kg'],
            ['param' => 'Water Flow Rate', 'spec' => '60-100 liters/minute'],
            ['param' => 'Standard Length', 'spec' => 'Custom (typically 15m - 60m loops)'],
            ['param' => 'Packaging', 'spec' => 'Wooden case or carton box'],
        ],
        'advantages' => [
            ['icon' => 'lightning', 'title' => 'Versatile Performance', 'desc' => 'Adaptable for multiple stone processing applications from primary quarrying to secondary finishing.'],
            ['icon' => 'coins', 'title' => 'Cost-Effective', 'desc' => 'Balanced price and performance ratio making it ideal for medium to large operations.'],
            ['icon' => 'shield-check', 'title' => 'Reliable Durability', 'desc' => 'Robust construction ensures consistent performance across varied stone hardness levels.'],
            ['icon' => 'paintbrush', 'title' => 'Precision Finishing', 'desc' => 'Fine bead spacing delivers superior surface finish reducing secondary processing needs.'],
            ['icon' => 'gears', 'title' => 'Customizable', 'desc' => 'Available in various diamond concentrations and bead configurations.'],
            ['icon' => 'headset', 'title' => 'Expert Support', 'desc' => 'Comprehensive technical guidance for optimal wire selection and operation.'],
        ],
        'guidelines' => [
            'installation' => [
                'Inspect wire condition before installation',
                'Maintain proper tension (700-1000 kg)',
                'Verify pulley alignment and cleanliness',
                'Ensure water cooling system readiness',
                'Run wire at moderate speed for initial seating',
            ],
            'operation' => [
                'Maintain linear speed of 30-35 m/s',
                'Ensure water flow of 60-100 liters/minute',
                'Monitor wire tension regularly',
                'Avoid sudden machine movements',
                'Check for vibrations and unusual sounds',
            ],
            'maintenance' => [
                'Clean wire and beads after operations',
                'Inspect pulleys for wear monthly',
                'Clear water system blockages',
                'Lubricate bearings as scheduled',
                'Store wire in dry conditions',
            ],
            'safety' => [
                'Always wear proper safety equipment',
                'Maintain safe distance from operating wire',
                'Never touch running wire',
                'Keep emergency stop accessible',
                'Train all operators on safety procedures',
            ],
        ],
        'relatedProducts' => [
            ['slug' => 'quarrying-wire-saw', 'title' => 'Quarrying Wire Saw', 'image' => 'assets/images/products/quarrying-wire.jpg', 'desc' => 'Heavy-duty wire saw for large-scale stone extraction.'],
            ['slug' => 'mono-wire', 'title' => 'Mono (Stationary) Wire', 'image' => 'assets/images/products/mono-wire.jpg', 'desc' => 'Stationary wire saw for precise cutting in stone processing.'],
            ['slug' => 'diamond-beads', 'title' => 'Diamond Wiresaw Beads', 'image' => 'assets/images/products/diamond-beads.jpg', 'desc' => 'Premium diamond beads for wire saw assembly and replacements.'],
        ],
        'contact' => [
            'phone1' => '+91 99288 11486',
            'phone2' => '+91 90240 34737',
            'email' => 'cdtools8189@gmail.com',
        ],
    ],

    'mono-wire' => [
        'id' => 'mono-wire',
        'name' => 'Mono (Stationary) Wire',
        'category' => 'Wire Saws',
        'hero' => [
            'image' => 'assets/images/products/mono-wire-hero.jpg',
            'tagline' => 'Precision Cutting',
            'description' => 'Stationary wire saw system for precise, controlled cutting operations in stone processing facilities. Maximum accuracy with minimal material wastage.',
        ],
        'quickStats' => [
            ['label' => 'Wire Diameter', 'value' => '8.5mm'],
            ['label' => 'Bead Density', 'value' => '50 beads/m'],
            ['label' => 'Tensile Strength', 'value' => '1800 MPa'],
            ['label' => 'Cutting Speed', 'value' => '10-20 m²/h'],
        ],
        'overview' => [
            'mainImage' => 'assets/images/products/mono-wire-main.jpg',
            'badge' => 'Made in India',
            'galleryImages' => [
                'assets/images/products/mono-wire-detail-1.jpg',
                'assets/images/products/mono-wire-detail-2.jpg',
                'assets/images/products/mono-wire-detail-3.jpg',
            ],
            'title' => 'Stationary Precision System',
            'description1' => 'Our Mono Wire is specifically designed for stationary wire saw machines used in stone processing facilities. With precision engineering and fine bead spacing, it delivers exceptional cutting accuracy for slab cutting, trimming, and profiling operations.',
            'description2' => 'Ideal for facilities requiring high-precision cuts with minimal material loss. The fine bead configuration ensures smooth surface finish while maintaining excellent wire life and consistent performance across extended cutting sessions.',
            'keyFeatures' => [
                ['title' => 'Fine Bead Spacing', 'desc' => '50 beads per meter for ultra-precise cuts'],
                ['title' => 'Excellent Surface Finish', 'desc' => 'Smooth cutting surface requiring minimal post-processing'],
                ['title' => 'Stable Performance', 'desc' => 'Designed for stationary machines with consistent tension'],
                ['title' => 'Material Efficiency', 'desc' => 'Minimal kerf width reduces material wastage significantly'],
            ],
            'certifications' => 'ISO 9001:2015 | CE Certified | 100% Quality Tested',
        ],
        'applications' => [
            ['title' => 'Slab Cutting', 'image' => 'assets/images/applications/slab-cutting.jpg', 'desc' => 'Precise cross-cutting of stone slabs with smooth surfaces and tight tolerances.'],
            ['title' => 'Trim Operations', 'image' => 'assets/images/applications/trim-operations.jpg', 'desc' => 'Accurate trimming of edges and removal of defective sections.'],
            ['title' => 'Panel Cutting', 'image' => 'assets/images/applications/panel-cutting.jpg', 'desc' => 'Cutting large panels into smaller sections with precision alignment.'],
            ['title' => 'Countertop Production', 'image' => 'assets/images/applications/countertop.jpg', 'desc' => 'Creating finished countertops with precise dimensions and smooth edges.'],
            ['title' => 'Stone Flooring', 'image' => 'assets/images/applications/stone-flooring.jpg', 'desc' => 'Cutting stone flooring tiles with exact specifications and quality finish.'],
            ['title' => 'Specialty Cutting', 'image' => 'assets/images/applications/specialty-cutting.jpg', 'desc' => 'Custom cuts for decorative and architectural stone applications.'],
        ],
        'specifications' => [
            ['param' => 'Wire Diameter', 'spec' => '8.5mm ± 0.15mm'],
            ['param' => 'Bead Diameter', 'spec' => '8.0mm - 8.5mm'],
            ['param' => 'Bead Spacing', 'spec' => '50 beads/meter'],
            ['param' => 'Wire Rope Construction', 'spec' => '7×7 structure'],
            ['param' => 'Breaking Load (Tensile Strength)', 'spec' => '≥ 1800 MPa (≥ 1800 kg)'],
            ['param' => 'Diamond Concentration', 'spec' => '35% - 40% (customizable)'],
            ['param' => 'Diamond Mesh Size', 'spec' => '45/50, 50/60, 60/70, 70/80'],
            ['param' => 'Bead Connection Method', 'spec' => 'Injection molding (premium quality)'],
            ['param' => 'Cutting Speed', 'spec' => '10-20 m²/hour'],
            ['param' => 'Lifespan (Average Stone)', 'spec' => '1500-2000 m² per wire'],
            ['param' => 'Recommended Cutting Speed', 'spec' => '32-38 m/s (linear speed)'],
            ['param' => 'Recommended Wire Tension', 'spec' => '600-900 kg'],
            ['param' => 'Water Flow Rate', 'spec' => '40-80 liters/minute'],
            ['param' => 'Standard Length', 'spec' => 'Custom (typically 10m - 50m loops)'],
            ['param' => 'Packaging', 'spec' => 'Protective carton box'],
        ],
        'advantages' => [
            ['icon' => 'lightning', 'title' => 'Precision Cutting', 'desc' => 'Delivers tight tolerances and exact dimensions for finished stone products.'],
            ['icon' => 'coins', 'title' => 'Material Efficiency', 'desc' => 'Fine kerf width minimizes material loss and waste.'],
            ['icon' => 'shield-check', 'title' => 'Superior Finish', 'desc' => 'Smooth surface finish eliminates need for additional polishing.'],
            ['icon' => 'paintbrush', 'title' => 'Consistent Quality', 'desc' => 'Stationary operation ensures repeatable, reliable results.'],
            ['icon' => 'gears', 'title' => 'Long Lifespan', 'desc' => 'Extended service life due to optimized design for stationary use.'],
            ['icon' => 'headset', 'title' => 'Full Support', 'desc' => 'Complete technical guidance for facility integration and optimization.'],
        ],
        'guidelines' => [
            'installation' => [
                'Install in rigid, stable stationary frame',
                'Ensure level mounting of machine components',
                'Set precise tension parameters (600-900 kg)',
                'Verify water circulation system integrity',
                'Calibrate cutting guides for accuracy',
            ],
            'operation' => [
                'Maintain linear speed of 32-38 m/s',
                'Ensure steady water flow of 40-80 liters/minute',
                'Keep wire tension consistent throughout operation',
                'Allow gradual acceleration and deceleration',
                'Monitor cutting resistance continuously',
            ],
            'maintenance' => [
                'Clean wire and beads after each cutting session',
                'Inspect machine alignment monthly',
                'Clean water nozzles and circulation lines',
                'Check structural stability regularly',
                'Replace water filters as needed',
            ],
            'safety' => [
                'Ensure machine is properly guarded',
                'Wear safety glasses and protective equipment',
                'Keep hands away from cutting area',
                'Verify emergency stop functionality',
                'Train operators on stationary machine safety',
            ],
        ],
        'relatedProducts' => [
            ['slug' => 'quarrying-wire-saw', 'title' => 'Quarrying Wire Saw', 'image' => 'assets/images/products/quarrying-wire.jpg', 'desc' => 'Heavy-duty wire saw for large-scale stone extraction.'],
            ['slug' => 'diamond-wire-saw', 'title' => 'Diamond Wire Saw', 'image' => 'assets/images/products/diamond-wire.jpg', 'desc' => 'Multi-purpose diamond wire for block squaring and profiling.'],
            ['slug' => 'diamond-beads', 'title' => 'Diamond Wiresaw Beads', 'image' => 'assets/images/products/diamond-beads.jpg', 'desc' => 'Premium beads for wire saw assembly and replacements.'],
        ],
        'contact' => [
            'phone1' => '+91 99288 11486',
            'phone2' => '+91 90240 34737',
            'email' => 'cdtools8189@gmail.com',
        ],
    ],

    'squaring-wire-saw' => [
        'id' => 'squaring-wire-saw',
        'name' => 'Squaring Wire Saw',
        'category' => 'Wire Saws',
        'hero' => [
            'image' => 'assets/images/products/squaring-wire-hero.jpg',
            'tagline' => 'Block Preparation',
            'description' => 'Specialized wire saw engineered specifically for block squaring operations. Delivers perfect right angles and uniform surfaces with minimal material loss.',
        ],
        'quickStats' => [
            ['label' => 'Wire Diameter', 'value' => '11.0mm'],
            ['label' => 'Bead Density', 'value' => '42 beads/m'],
            ['label' => 'Tensile Strength', 'value' => '2150 MPa'],
            ['label' => 'Cutting Speed', 'value' => '6-12 m²/h'],
        ],
        'overview' => [
            'mainImage' => 'assets/images/products/squaring-wire-main.jpg',
            'badge' => 'Made in India',
            'galleryImages' => [
                'assets/images/products/squaring-wire-detail-1.jpg',
                'assets/images/products/squaring-wire-detail-2.jpg',
                'assets/images/products/squaring-wire-detail-3.jpg',
            ],
            'title' => 'Professional Block Squaring',
            'description1' => 'Our Squaring Wire Saw is specifically optimized for block squaring operations where precision angles and uniform surfaces are critical. With balanced bead distribution and medium tensile strength, it ensures perfect squaring with minimal material wastage.',
            'description2' => 'Designed for quarry and processing facilities focusing on block preparation, this wire delivers consistent performance for creating market-ready blocks. The optimized geometry ensures square edges and flat surfaces that meet industry standards.',
            'keyFeatures' => [
                ['title' => 'Perfect Right Angles', 'desc' => 'Engineered for precise 90-degree cuts on all sides'],
                ['title' => 'Uniform Surface Quality', 'desc' => '42 beads/m spacing ensures even cutting surface'],
                ['title' => 'High Cutting Power', 'desc' => '2150 MPa tensile strength handles hard stones'],
                ['title' => 'Minimal Material Loss', 'desc' => 'Optimized kerf width reduces waste in block preparation'],
            ],
            'certifications' => 'ISO 9001:2015 | CE Certified | 100% Quality Tested',
        ],
        'applications' => [
            ['title' => 'Granite Block Squaring', 'image' => 'assets/images/applications/granite-squaring.jpg', 'desc' => 'Create perfect square blocks from rough granite quarry material.'],
            ['title' => 'Marble Block Preparation', 'image' => 'assets/images/applications/marble-squaring.jpg', 'desc' => 'Square marble blocks with precision angles and smooth surfaces.'],
            ['title' => 'Limestone Processing', 'image' => 'assets/images/applications/limestone-squaring.jpg', 'desc' => 'Efficient squaring of limestone and sandstone blocks.'],
            ['title' => 'Dimensional Blocks', 'image' => 'assets/images/applications/dimensional-blocks.jpg', 'desc' => 'Cut blocks to exact dimensions for further processing.'],
            ['title' => 'Multiple Face Cutting', 'image' => 'assets/images/applications/multi-face-cutting.jpg', 'desc' => 'Square multiple faces of blocks in single operation.'],
            ['title' => 'Quality Grading', 'image' => 'assets/images/applications/quality-grading.jpg', 'desc' => 'Prepare blocks that meet premium quality standards for export.'],
        ],
        'specifications' => [
            ['param' => 'Wire Diameter', 'spec' => '11.0mm ± 0.2mm'],
            ['param' => 'Bead Diameter', 'spec' => '10.2mm - 10.8mm'],
            ['param' => 'Bead Spacing', 'spec' => '42 beads/meter'],
            ['param' => 'Wire Rope Construction', 'spec' => '6×19 + 1 FC structure'],
            ['param' => 'Breaking Load (Tensile Strength)', 'spec' => '≥ 2150 MPa (≥ 2400 kg)'],
            ['param' => 'Diamond Concentration', 'spec' => '27% - 32% (customizable)'],
            ['param' => 'Diamond Mesh Size', 'spec' => '32/37, 37/42, 42/47'],
            ['param' => 'Bead Connection Method', 'spec' => 'Injection molding / Rubber + Spring'],
            ['param' => 'Cutting Speed', 'spec' => '6-12 m²/hour'],
            ['param' => 'Lifespan (Mixed Stone)', 'spec' => '1100-1600 m² per wire'],
            ['param' => 'Recommended Cutting Speed', 'spec' => '28-33 m/s (linear speed)'],
            ['param' => 'Recommended Wire Tension', 'spec' => '750-1150 kg'],
            ['param' => 'Water Flow Rate', 'spec' => '70-110 liters/minute'],
            ['param' => 'Standard Length', 'spec' => 'Custom (typically 18m - 70m loops)'],
            ['param' => 'Packaging', 'spec' => 'Wooden case or carton box'],
        ],
        'advantages' => [
            ['icon' => 'lightning', 'title' => 'Perfect Geometry', 'desc' => 'Delivers precise right angles and uniform cutting surfaces consistently.'],
            ['icon' => 'coins', 'title' => 'Reduced Waste', 'desc' => 'Optimized cutting design minimizes material loss during squaring.'],
            ['icon' => 'shield-check', 'title' => 'Reliable Performance', 'desc' => 'High tensile strength handles demanding block squaring operations.'],
            ['icon' => 'paintbrush', 'title' => 'Market-Ready Blocks', 'desc' => 'Produces blocks that meet industry standards and quality requirements.'],
            ['icon' => 'gears', 'title' => 'Specialized Design', 'spec' => 'Purpose-built for block squaring with optimized specifications.'],
            ['icon' => 'headset', 'title' => 'Technical Support', 'desc' => 'Expert guidance for optimal squaring performance and results.'],
        ],
        'guidelines' => [
            'installation' => [
                'Mount machine on stable, level foundation',
                'Set wire tension at 750-1150 kg for optimal squaring',
                'Verify square alignment of cutting guides',
                'Ensure water system provides steady flow',
                'Test wire with low-speed run before full operation',
            ],
            'operation' => [
                'Maintain linear speed of 28-33 m/s',
                'Ensure continuous water supply of 70-110 liters/minute',
                'Monitor wire tension throughout squaring operation',
                'Use cutting guides for precise angle control',
                'Check for vibrations that affect squaring accuracy',
            ],
            'maintenance' => [
                'Clean wire thoroughly after each block',
                'Inspect cutting guides for alignment weekly',
                'Check water nozzles for proper coverage',
                'Lubricate machine bearings as scheduled',
                'Verify structural rigidity of machine frame',
            ],
            'safety' => [
                'Ensure proper machine guarding is in place',
                'Wear protective equipment during operations',
                'Maintain safe distance from cutting wire',
                'Keep emergency stop easily accessible',
                'Train operators on block squaring safety procedures',
            ],
        ],
        'relatedProducts' => [
            ['slug' => 'quarrying-wire-saw', 'title' => 'Quarrying Wire Saw', 'image' => 'assets/images/products/quarrying-wire.jpg', 'desc' => 'Heavy-duty wire saw for large-scale stone extraction.'],
            ['slug' => 'diamond-wire-saw', 'title' => 'Diamond Wire Saw', 'image' => 'assets/images/products/diamond-wire.jpg', 'desc' => 'Multi-purpose diamond wire for block squaring and profiling.'],
            ['slug' => 'diamond-beads', 'title' => 'Diamond Wiresaw Beads', 'image' => 'assets/images/products/diamond-beads.jpg', 'desc' => 'Premium beads for wire saw assembly and replacements.'],
        ],
        'contact' => [
            'phone1' => '+91 99288 11486',
            'phone2' => '+91 90240 34737',
            'email' => 'cdtools8189@gmail.com',
        ],
    ],

    'profiling-wire-saw' => [
        'id' => 'profiling-wire-saw',
        'name' => 'Profiling Wire Saw',
        'category' => 'Wire Saws',
        'hero' => [
            'image' => 'assets/images/products/profiling-wire-hero.jpg',
            'tagline' => 'Decorative Cutting',
            'description' => 'Advanced wire saw system for creating decorative profiles, beveled edges, and artistic cuts on stone surfaces. Deliver premium finished stone products with precision.',
        ],
        'quickStats' => [
            ['label' => 'Wire Diameter', 'value' => '9.5mm'],
            ['label' => 'Bead Density', 'value' => '48 beads/m'],
            ['label' => 'Tensile Strength', 'value' => '1950 MPa'],
            ['label' => 'Cutting Speed', 'value' => '7-14 m²/h'],
        ],
        'overview' => [
            'mainImage' => 'assets/images/products/profiling-wire-main.jpg',
            'badge' => 'Made in India',
            'galleryImages' => [
                'assets/images/products/profiling-wire-detail-1.jpg',
                'assets/images/products/profiling-wire-detail-2.jpg',
                'assets/images/products/profiling-wire-detail-3.jpg',
            ],
            'title' => 'Decorative Profiling Solution',
            'description1' => 'Our Profiling Wire Saw is engineered for creating decorative cuts, beveled edges, and complex profiles on stone surfaces. With fine bead spacing and precise diameter control, it enables artistic stone cutting for premium architectural applications.',
            'description2' => 'Perfect for high-end stone finishing, this wire combines artistic flexibility with reliable performance. The optimized design allows for curved cuts, stepped profiles, and decorative patterns while maintaining consistent quality throughout the cutting process.',
            'keyFeatures' => [
                ['title' => 'Fine Detail Capability', 'desc' => '48 beads/m enables intricate profile cutting'],
                ['title' => 'Smooth Finish Quality', 'desc' => 'Creates polished-like surfaces reducing finishing time'],
                ['title' => 'Versatile Profile Options', 'desc' => 'Can cut straight, curved, and decorative patterns'],
                ['title' => 'Premium Output', 'desc' => 'Produces finished stone ready for installation'],
            ],
            'certifications' => 'ISO 9001:2015 | CE Certified | 100% Quality Tested',
        ],
        'applications' => [
            ['title' => 'Beveled Edges', 'image' => 'assets/images/applications/beveled-edges.jpg', 'desc' => 'Create elegant beveled edges on countertops and architectural elements.'],
            ['title' => 'Decorative Profiles', 'image' => 'assets/images/applications/decorative-profiles.jpg', 'desc' => 'Cut decorative moldings and ornamental profiles on stone surfaces.'],
            ['title' => 'Curved Cutting', 'image' => 'assets/images/applications/curved-cutting.jpg', 'desc' => 'Create curved architectural elements and artistic designs.'],
            ['title' => 'Stepped Profiles', 'image' => 'assets/images/applications/stepped-profiles.jpg', 'desc' => 'Produce complex stepped and terraced stone designs.'],
            ['title' => 'Custom Designs', 'image' => 'assets/images/applications/custom-designs.jpg', 'desc' => 'Execute unique custom stone designs for high-end projects.'],
            ['title' => 'Architectural Stone', 'image' => 'assets/images/applications/architectural-stone.jpg', 'desc' => 'Perfect for architectural stone elements and premium finishes.'],
        ],
        'specifications' => [
            ['param' => 'Wire Diameter', 'spec' => '9.5mm ± 0.18mm'],
            ['param' => 'Bead Diameter', 'spec' => '9.0mm - 9.5mm'],
            ['param' => 'Bead Spacing', 'spec' => '48 beads/meter'],
            ['param' => 'Wire Rope Construction', 'spec' => '6×19 + 1 FC structure'],
            ['param' => 'Breaking Load (Tensile Strength)', 'spec' => '≥ 1950 MPa (≥ 2100 kg)'],
            ['param' => 'Diamond Concentration', 'spec' => '32% - 38% (customizable)'],
            ['param' => 'Diamond Mesh Size', 'spec' => '40/45, 45/50, 50/55, 55/60'],
            ['param' => 'Bead Connection Method', 'spec' => 'Premium injection molding'],
            ['param' => 'Cutting Speed', 'spec' => '7-14 m²/hour'],
            ['param' => 'Lifespan (Average Stone)', 'spec' => '1300-1900 m² per wire'],
            ['param' => 'Recommended Cutting Speed', 'spec' => '30-36 m/s (linear speed)'],
            ['param' => 'Recommended Wire Tension', 'spec' => '680-1050 kg'],
            ['param' => 'Water Flow Rate', 'spec' => '50-90 liters/minute'],
            ['param' => 'Standard Length', 'spec' => 'Custom (typically 12m - 55m loops)'],
            ['param' => 'Packaging', 'spec' => 'Premium protective carton box'],
        ],
        'advantages' => [
            ['icon' => 'lightning', 'title' => 'Fine Detail Cutting', 'desc' => 'Capable of producing intricate profiles and decorative patterns.'],
            ['icon' => 'coins', 'title' => 'Premium Quality Output', 'desc' => 'Creates finished stone that requires minimal additional processing.'],
            ['icon' => 'shield-check', 'title' => 'Consistent Results', 'desc' => 'Reliable performance for repeatable decorative cutting operations.'],
            ['icon' => 'paintbrush', 'title' => 'Design Versatility', 'desc' => 'Supports creative stone design and artistic expressions.'],
            ['icon' => 'gears', 'title' => 'Smooth Finishing', 'desc' => 'Superior surface quality similar to polished stone.'],
            ['icon' => 'headset', 'title' => 'Design Consultation', 'desc' => 'Expert guidance on profile design and cutting parameters.'],
        ],
        'guidelines' => [
            'installation' => [
                'Mount on rigid machine frame for profile accuracy',
                'Set precise tension at 680-1050 kg',
                'Install with accurate angular guides for profile control',
                'Ensure stable water circulation system',
                'Test with scrap stone before high-value profiles',
            ],
            'operation' => [
                'Maintain linear speed of 30-36 m/s',
                'Ensure water flow of 50-90 liters/minute for fine cutting',
                'Monitor wire tension for profile consistency',
                'Use guide systems for complex profile cuts',
                'Adjust tension for different profile depths',
            ],
            'maintenance' => [
                'Clean wire thoroughly after each profile operation',
                'Inspect guide systems for accuracy monthly',
                'Check water nozzles for proper mist coverage',
                'Verify profile guide alignment regularly',
                'Replace water filters frequently for fine cutting',
            ],
            'safety' => [
                'Ensure machine is properly guarded for complex cuts',
                'Wear all protective equipment during operation',
                'Keep hands away from cutting area',
                'Maintain emergency stop accessibility',
                'Train operators on profile cutting safety',
            ],
        ],
        'relatedProducts' => [
            ['slug' => 'diamond-wire-saw', 'title' => 'Diamond Wire Saw', 'image' => 'assets/images/products/diamond-wire.jpg', 'desc' => 'Multi-purpose diamond wire for block squaring and profiling.'],
            ['slug' => 'mono-wire', 'title' => 'Mono (Stationary) Wire', 'image' => 'assets/images/products/mono-wire.jpg', 'desc' => 'Stationary wire saw for precise cutting in stone processing.'],
            ['slug' => 'diamond-beads', 'title' => 'Diamond Wiresaw Beads', 'image' => 'assets/images/products/diamond-beads.jpg', 'desc' => 'Premium beads for wire saw assembly and replacements.'],
        ],
        'contact' => [
            'phone1' => '+91 99288 11486',
            'phone2' => '+91 90240 34737',
            'email' => 'cdtools8189@gmail.com',
        ],
    ],

    'diamond-beads' => [
        'id' => 'diamond-beads',
        'name' => 'Diamond Wiresaw Beads',
        'category' => 'Accessories',
        'hero' => [
            'image' => 'assets/images/products/diamond-beads-hero.jpg',
            'tagline' => 'Replacement Beads',
            'description' => 'Premium diamond beads for wire saw assembly and replacement. High-quality electroplated diamond beads engineered for superior cutting performance and extended service life.',
        ],
        'quickStats' => [
            ['label' => 'Diamond Grade', 'value' => 'Industrial'],
            ['label' => 'Concentration Range', 'value' => '25% - 40%'],
            ['label' => 'Mesh Sizes', 'value' => '30/35 to 80/100'],
            ['label' => 'Connection Types', 'value' => 'Multiple Options'],
        ],
        'overview' => [
            'mainImage' => 'assets/images/products/diamond-beads-main.jpg',
            'badge' => 'Made in India',
            'galleryImages' => [
                'assets/images/products/diamond-beads-detail-1.jpg',
                'assets/images/products/diamond-beads-detail-2.jpg',
                'assets/images/products/diamond-beads-detail-3.jpg',
            ],
            'title' => 'Premium Diamond Bead Solutions',
            'description1' => 'Our Diamond Wiresaw Beads are manufactured using advanced electroplating technology to ensure optimal diamond retention and cutting performance. Each bead is precision-engineered to exact specifications for consistency and reliability in all stone cutting applications.',
            'description2' => 'Available in various diamond concentrations and mesh sizes, our beads can be customized to match specific stone types, cutting speeds, and application requirements. We provide both individual bead replacements and complete bead sets for wire assembly.',
            'keyFeatures' => [
                ['title' => 'High-Quality Diamonds', 'desc' => 'Industrial-grade diamonds selected for superior cutting performance'],
                ['title' => 'Superior Bonding', 'desc' => 'Advanced electroplating ensures excellent diamond retention'],
                ['title' => 'Wide Range', 'desc' => 'Multiple concentrations and mesh sizes available'],
                ['title' => 'Customizable', 'desc' => 'Tailored solutions for specific stone types and applications'],
            ],
            'certifications' => 'ISO 9001:2015 | CE Certified | 100% Quality Tested',
        ],
        'applications' => [
            ['title' => 'Wire Saw Assembly', 'image' => 'assets/images/applications/wire-assembly.jpg', 'desc' => 'Complete beads for assembling new diamond wire saws.'],
            ['title' => 'Bead Replacement', 'image' => 'assets/images/applications/bead-replacement.jpg', 'desc' => 'Replacement beads for maintaining existing wire saws.'],
            ['title' => 'Quarrying Operations', 'image' => 'assets/images/applications/quarry-ops.jpg', 'desc' => 'Heavy-duty beads for high-volume quarrying applications.'],
            ['title' => 'Stone Processing', 'image' => 'assets/images/applications/stone-process.jpg', 'desc' => 'Precision beads for secondary stone processing facilities.'],
            ['title' => 'Specialty Applications', 'image' => 'assets/images/applications/specialty-apps.jpg', 'desc' => 'Custom beads for specific stone types and unique requirements.'],
            ['title' => 'OEM Supplies', 'image' => 'assets/images/applications/oem-supplies.jpg', 'desc' => 'Wholesale bead supplies for wire saw manufacturers.'],
        ],
        'specifications' => [
            ['param' => 'Diamond Grade', 'spec' => 'Industrial (Multi-crystalline)'],
            ['param' => 'Diamond Concentration Range', 'spec' => '25% - 40% (customizable)'],
            ['param' => 'Mesh Size Options', 'spec' => '30/35, 35/40, 40/45, 45/50, 50/60, 60/70, 70/80, 80/100'],
            ['param' => 'Bead Diameter Range', 'spec' => '8.0mm - 11.0mm (multiple sizes)'],
            ['param' => 'Connection Methods', 'spec' => 'Electroplated / Injection Molded / Rubber+Spring'],
            ['param' => 'Plating Material', 'spec' => 'Copper-Nickel alloy for superior durability'],
            ['param' => 'Bonding Technology', 'spec' => 'Advanced electroplating process'],
            ['param' => 'Quality Control', 'spec' => '100% visual inspection + performance testing'],
            ['param' => 'Availability', 'spec' => 'Individual beads or complete sets'],
            ['param' => 'Customization', 'spec' => 'Available for specific applications'],
            ['param' => 'Storage Life', 'spec' => '5+ years in proper storage conditions'],
            ['param' => 'Packaging Options', 'spec' => 'Bulk boxes, cartons, or custom packaging'],
            ['param' => 'Lead Time', 'spec' => '7-14 days for custom specifications'],
            ['param' => 'Minimum Order Quantity', 'spec' => 'Available for wholesale and retail'],
            ['param' => 'Warranty', 'spec' => 'Quality guaranteed, tested before shipment'],
        ],
        'advantages' => [
            ['icon' => 'lightning', 'title' => 'Superior Cutting Power', 'desc' => 'High-quality diamonds deliver exceptional cutting performance.'],
            ['icon' => 'coins', 'title' => 'Cost-Effective', 'desc' => 'Replacement beads extend wire life economically.'],
            ['icon' => 'shield-check', 'title' => 'Reliable Quality', 'desc' => '100% quality tested for consistent performance.'],
            ['icon' => 'paintbrush', 'title' => 'Fully Customizable', 'desc' => 'Available in multiple concentrations and mesh sizes.'],
            ['icon' => 'gears', 'title' => 'Easy Installation', 'desc' => 'Compatible with standard wire saw equipment.'],
            ['icon' => 'headset', 'title' => 'Expert Consultation', 'desc' => 'Technical guidance on bead selection and specifications.'],
        ],
        'guidelines' => [
            'installation' => [
                'Inspect beads for damage before installation',
                'Ensure wire is clean before bead attachment',
                'Use proper tools for secure bead mounting',
                'Verify spacing between beads is uniform',
                'Test wire tension before operation',
            ],
            'operation' => [
                'Allow gradual speed increase when using new beads',
                'Monitor cutting performance during initial use',
                'Maintain proper water cooling throughout operation',
                'Monitor wire tension with new bead sets',
                'Check bead retention periodically',
            ],
            'maintenance' => [
                'Clean beads regularly to remove stone dust',
                'Inspect beads for wear and diamond loss',
                'Replace damaged or worn beads immediately',
                'Store replacement beads in dry conditions',
                'Keep detailed records of bead performance',
            ],
            'safety' => [
                'Handle beads carefully to prevent damage',
                'Wear gloves when working with wire and beads',
                'Keep beads away from rotating equipment',
                'Never attempt bead replacement during operation',
                'Follow proper wire saw safety procedures',
            ],
        ],
        'relatedProducts' => [
            ['slug' => 'quarrying-wire-saw', 'title' => 'Quarrying Wire Saw', 'image' => 'assets/images/products/quarrying-wire.jpg', 'desc' => 'Heavy-duty wire saw for large-scale stone extraction.'],
            ['slug' => 'diamond-wire-saw', 'title' => 'Diamond Wire Saw', 'image' => 'assets/images/products/diamond-wire.jpg', 'desc' => 'Multi-purpose diamond wire for block squaring and profiling.'],
            ['slug' => 'mono-wire', 'title' => 'Mono (Stationary) Wire', 'image' => 'assets/images/products/mono-wire.jpg', 'desc' => 'Stationary wire saw for precise cutting in stone processing.'],
        ],
        'contact' => [
            'phone1' => '+91 99288 11486',
            'phone2' => '+91 90240 34737',
            'email' => 'cdtools8189@gmail.com',
        ],
    ],
];

// Get product by slug
function getProduct($slug) {
    global $products;
    return isset($products[$slug]) ? $products[$slug] : null;
}

// Get all products
function getAllProducts() {
    global $products;
    return $products;
}
?>
